### ISSUE TITLE
App install under subdomain with nginx as proxy

### ISSUE THREAD

**Issue by macbroadcast** [loowid/loowid#85]
enhancement

**Comment by juanjmerono** [comment]
Could you create a docker image to be able to test this configuration under ngnix?

**Comment by macbroadcast** [comment]
hello @juanjmerono , I am moving my stuff to a new registrar and i set up all node apps on one digital ocean droplet today, because i need to save money ;) It would be great if there is a ways to  bypass (comment out)  the https /cert stuff, till i have more time to investigate and other people join your project, that don´t use #openshift . I would love to run your project on loowid.let.de because i have lots of traffic , lets make 2015 the #WebRTC year ! Thanks for your patience with me.

**Comment by juanjmerono** [comment]
Sounds promissing @macbroadcast !! I'm going to add more startup options like --https=false or --mongodb=false to control when run https or mongodb as part of loowid startup. Sounds good?

Thanks !!

**Comment by macbroadcast** [comment]
Sounds great @juanjmerono ! , i really appreciate the efford you put into the project :+1:

**Comment by juanjmerono** [comment]
In the readme are the details to control everything. With --port, --sport and --bport if you want to startup more than one loowid server. Now in master (and soon in next release) if certificate files are not present the server startup without ssl. Please try to run master branch and let us know if works !!

**Comment by macbroadcast** [comment]
Since i want to run loowid  with nginx on port 3000 , i gave it a try on the weekend, everything worked seamless on my local machine running ubuntu 14.10 

![14 10](https://cloud.githubusercontent.com/assets/7961/6777675/14777d84-d14c-11e4-8dd9-49fd8484b1b9.jpg)

but no luck on my digital ocean droplet running Ubuntu 14.04.1 LTS , i used exactly the same steps ``` 

#:~/loowid# grunt

/root/loowid/node_modules/grunt/node_modules/lodash/lodash.js:182
});
   
SyntaxError: Unexpected end of input
  at Module._compile (module.js:439:25)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/root/loowid/node_modules/grunt/lib/grunt/util.js:30:18)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at gRequire (/root/loowid/node_modules/grunt/lib/grunt.js:23:24)
  at Object.<anonymous> (/root/loowid/node_modules/grunt/lib/grunt.js:25:12)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:45:1)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3
```

i also removed the node modules and cleaned npm cache and reinstalled, any other idea ?

Thanks

**Comment by juanjmerono** [comment]
It's really weird. 
You are running "grunt" in production but it's better use "grunt prod" or "npm start" instead.
Also you aren't using any parameter in production, so you are going to run using default ports (and without nginx I guess), but I think you already know it because you type --port=3000 in local environment to work with nginx. Are you testing locally a different deployment than in production?

Please, can you describe me what is your production deployment to let me understand how could loowid run on it and where is the problem?

**Comment by macbroadcast** [comment]
It doesnt matter if i type "grunt" for testing ,this was my purpose, "grunt prod" or "npm start" , it allways gives me the above error. But on my local ubuntu 14.10 its npm version 1.4.28 and on the production  system (14.04.1 LTS)  its npm version 2.7.3, furthermore the local mongod version is 2.6.5 and on production its 3.0.1 could this cause the problem ? Thanks

**Comment by juanjmerono** [comment]
I've tested with all these versions in os x:
npm 2.7.3/1.4.28, 
mongo 2.6.5/3.0.1, 
node 0.10/0.12 
and it works with all of them !!

Could you type "grunt --verbose" to get more info about the error?

**Comment by sinmsinm** [comment]
I tried to install in a digital ocean droplet. Nginx attending 80 and 443, 80 requests were redirected to 443 and 443 proxied to loowid runing to a prod mode on 8080.  It was fine but a bit tricky. I had to change the prod line in gruntfile to start it at 8080 instead of 80 in prod mode. and define WS_PORT variable to make client wss requests be addressed to the 443.  Just it... 

After that, I think that Marc issues were related with the low free memory in the droplet that make loowid run bad. I close the issue, but if we recollect more info we can reopen it. @macbroadcast  Do you agree? Thanks for all this feedback

**Comment by macbroadcast** [comment]
Yes its ok @sinmsinm , sorry that i decided to use another solution, my main problem, beside the installation and memory problem with my droplet was that i need a permanent room URL, where people can click and are connected to MY ROOM, the solution i found is by far not so enhanced and look so sexy as loowid, but i need something that worked out of the box. I will of course follow your development and try loowid again :)
